// Static product catalog derived from the list you provided.
export const PRODUCTS = [
  {
    id: "BBB0893",
    category: "Bakery Mixes",
    name: "Blueberry Bits",
    code: "BBB0893",
  },
  {
    id: "BBB563",
    category: "Bakery Mixes",
    name: "Blueberry Bits Flav-R Bites",
    code: "BBB563",
  },
  {
    id: "CNB00876",
    category: "Bakery Mixes",
    name: "Cinnamon Flav-R Bites",
    code: "CNB00876",
  },
  {
    id: "SBB00842",
    category: "Bakery Mixes",
    name: "Strawberry Flav-R Bites",
    code: "SBB00842",
  },

  {
    id: "FCSV0100",
    category: "Grits & Flours",
    name: "Cassava Flour",
    code: "FCSV0100",
  },
  {
    id: "CM3500",
    category: "Grits & Flours",
    name: "Corn Grits",
    code: "CM3500",
  },
  {
    id: "POC4244",
    category: "Grits & Flours",
    name: "Popping Corn",
    code: "POC4244",
  },
  {
    id: "RFB0056",
    category: "Grits & Flours",
    name: "Rice Flour – Brown",
    code: "RFB0056",
  },
  {
    id: "RFW0055",
    category: "Grits & Flours",
    name: "Rice Flour – White",
    code: "RFW0055",
  },
  {
    id: "SGR8930",
    category: "Grits & Flours",
    name: "Soy Grits",
    code: "SGR8930",
  },

  { id: "GG001", category: "Gums & Binding", name: "Guar Gum", code: "GG001" },
  {
    id: "PCIB792",
    category: "Gums & Binding",
    name: "Insta Pure Cote B792",
    code: "PCIB792",
  },
  {
    id: "PCB790",
    category: "Gums & Binding",
    name: "Pure Cote B70",
    code: "PCB790",
  },
  {
    id: "SCDF42420",
    category: "Gums & Binding",
    name: "Sodium Citrate",
    code: "SCDF42420",
  },
  {
    id: "GXAN0013",
    category: "Gums & Binding",
    name: "Xanthan Gum",
    code: "GXAN0013",
  },

  {
    id: "CCS0185",
    category: "Proteins & Starches",
    name: "Corn Starch",
    code: "CCS0185",
  },
  {
    id: "SMT0523",
    category: "Proteins & Starches",
    name: "Modified Tapioca Starch",
    code: "SMT0523",
  },
  {
    id: "MWCS2020",
    category: "Proteins & Starches",
    name: "Modified Waxy Corn Starch",
    code: "MWCS2020",
  },
  {
    id: "NTS0059",
    category: "Proteins & Starches",
    name: "Native Tapioca Starch",
    code: "NTS0059",
  },
  {
    id: "PPS0085",
    category: "Proteins & Starches",
    name: "Pea Protein",
    code: "PPS0085",
  },
  {
    id: "SPT0596",
    category: "Proteins & Starches",
    name: "Potato Starch",
    code: "SPT0596",
  },
  {
    id: "WG4016",
    category: "Proteins & Starches",
    name: "Vital Wheat Gluten",
    code: "WG4016",
  },

  {
    id: "BLKS0059",
    category: "Seeds",
    name: "Black Sesame Seeds",
    code: "BLKS0059",
  },
  { id: "CHIA0811", category: "Seeds", name: "Chia Seeds", code: "CHIA0811" },
  {
    id: "FSB0015",
    category: "Seeds",
    name: "Flax Seeds – Brown",
    code: "FSB0015",
  },
  {
    id: "FSGD014",
    category: "Seeds",
    name: "Flax Seeds – Golden",
    code: "FSGD014",
  },
  {
    id: "GNT053006",
    category: "Seeds",
    name: "Hulled Sesame Seeds",
    code: "GNT053006",
  },
  {
    id: "HM41029",
    category: "Seeds",
    name: "Hulled White Millet",
    code: "HM41029",
  },
  {
    id: "NSS0014",
    category: "Seeds",
    name: "Natural Sesame Seeds",
    code: "NSS0014",
  },
  {
    id: "PSB0007",
    category: "Seeds",
    name: "Poppy Seeds – Blue",
    code: "PSB0007",
  },
  {
    id: "SPW0005",
    category: "Seeds",
    name: "Poppy Seeds – White",
    code: "SPW0005",
  },
  {
    id: "HPS0093",
    category: "Seeds",
    name: "Pumpkin Seeds Kernels",
    code: "HPS0093",
  },
  {
    id: "SFS0050",
    category: "Seeds",
    name: "Sunflower Seeds – Jumbo",
    code: "SFS0050",
  },
  {
    id: "SFS013",
    category: "Seeds",
    name: "Sunflower Seeds – Midget",
    code: "SFS013",
  },
  {
    id: "SHSS0058",
    category: "Seeds",
    name: "Sunflower Seeds – Shell",
    code: "SHSS0058",
  },

  {
    id: "DXT0086",
    category: "Sugars & Sweeteners",
    name: "Dextrose – Mono",
    code: "DXT0086",
  },
  {
    id: "ICING-C16",
    category: "Sugars & Sweeteners",
    name: "Icing Sugar C-16",
    code: "ICING-C16",
  },
  {
    id: "DEXP0023",
    category: "Sugars & Sweeteners",
    name: "Dextrose – Poly",
    code: "DEXP0023",
  },
];
